### ISSUE TITLE
Matplotlib 3.7 compatibility

### ISSUE THREAD

**Issue by joannadiong** [MartinHeroux/pliffy#25]
**Description**
Running `from pliffy import PliffyInfoABD, plot_abd` on Matplotlib v3.7  generates the error:
`ModuleNotFoundError: No module named 'matplotlib.axes._subplots'`

This seems a known problem:
[https://bugzilla.redhat.com/show_bug.cgi?id=2210605](https://bugzilla.redhat.com/show_bug.cgi?id=2210605)

The problem can be rectified by downgrading Matplotlib to v3.6.3, which might be the simplest solution for now.

**Comment by MartinHeroux** [comment]
Thanks for flagging. I have the same issue with the plotting in spike2py. It simply relates to type hinting, and is easily fixed. Best to keep up with the times and make the fix. Will address the issue and testing things before pushing and making a new release.

**Comment by MartinHeroux** [comment]
Hummm... I just created a fresh Python environment with Python 3.11 and install pliffy using `pip install pliffy`.
pip download Matplotlib v 3.7.2.

```bash
(venv) 19:29 ~/.../pliffy$ pip list
Package         Version
--------------- -------
contourpy       1.1.0
cycler          0.11.0
fonttools       4.42.1
kiwisolver      1.4.5
matplotlib      3.7.2
numpy           1.25.2
packaging       23.1
Pillow          10.0.0
pip             23.1.2
pliffy          0.1.3
pyparsing       3.0.9
python-dateutil 2.8.2
scipy           1.11.2
setuptools      65.5.0
six             1.16.0
```

I then ran the pliffy demo and it worked without error.

```python

>>> import pliffy
>>> pliffy.demo.demo()
```

Can I confirm what version of pliffy you are using. Also, can you send along a working example that causes this issue. It might be that the demo code does not access the part of the code that is causing the error.

**Comment by joannadiong** [comment]
Thanks Marty. Likewise, I ran a fresh install of pliffy on Python 3.10. Below are the tracebacks and package versions. Hope this provides some clues?

```
(env) [21:09] ~/.../temp$ python
Python 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from pliffy import PliffyInfoABD, plot_abd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/__init__.py", line 2, in <module>
    from . import plot
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/plot.py", line 1, in <module>
    from pliffy import estimate, parser, utils, figure
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/figure/__init__.py", line 2, in <module>
    from .figure_ab import FigureAB
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/figure/figure_ab.py", line 6, in <module>
    from matplotlib.axes._subplots import Subplot
ModuleNotFoundError: No module named 'matplotlib.axes._subplots'

>>> import pliffy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/__init__.py", line 2, in <module>
    from . import plot
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/plot.py", line 1, in <module>
    from pliffy import estimate, parser, utils, figure
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/figure/__init__.py", line 2, in <module>
    from .figure_ab import FigureAB
  File "/home/joanna/Desktop/temp/env/lib/python3.10/site-packages/pliffy/figure/figure_ab.py", line 6, in <module>
    from matplotlib.axes._subplots import Subplot
ModuleNotFoundError: No module named 'matplotlib.axes._subplots'

(env) [21:10] ~/.../temp$ pip list
Package         Version
--------------- -------
contourpy       1.1.0
cycler          0.11.0
fonttools       4.42.1
kiwisolver      1.4.5
matplotlib      3.7.2
numpy           1.25.2
packaging       23.1
Pillow          10.0.0
pip             22.3.1
pliffy          0.1.3
pyparsing       3.0.9
python-dateutil 2.8.2
scipy           1.11.2
setuptools      65.5.0
six             1.16.0
(env) [21:11] ~/.../temp$ python --version
Python 3.10.9
```

**Comment by MartinHeroux** [comment]
I see that I made the fix locally, and maybe when I tried to pip install
last week to test things, pip used my local (correct) copy.

I have made a new version (0.1.4) and pushed it to pypi (and also updated
the repo).

This should fix the problem (works for me on a fresh env). Let me know.

Marty

**Comment by joannadiong** [comment]
Wonderful, that worked, thanks!
